apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trino
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trino
spec:
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
  endpoints:
  - port: metrics
    interval: 10s
    path: /

---

apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trino
spec:
  ports:
    - name: metrics
      port: 3900
      targetPort: 49215
      protocol: TCP
  type: ClusterIP
  clusterIP: None

---

apiVersion: v1
kind: Endpoints
metadata:
  name: trino
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trino
subsets:
  - addresses:
    - ip: 192.168.182.110
    ports:
    - name: metrics
      port: 49215
      protocol: TCP
